spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pizza_express?useUnicode=true&characterEncoding=UTF8
    username: root
    password: yintaoAAZ2524
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
      maximum-pool-size: 10
      connection-test-query: SELECT 1